name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "rust_dev" ]
  pull_request:
    branches: [ "rust_dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust target
      run: rustup target add thumbv7em-none-eabihf
      
    - name: Build
      working-directory: ./rustdev
      run: cargo build --verbose
# No tests currently
#    - name: Run tests
#      working-directory: ./rustdev
#      run: cargo test --verbose
